### ISSUE TITLE
Build does not trigger on update

### ISSUE THREAD

**Issue by chmue** [LSE-Methodology/MY451#12]
@jacksojp made some changes yesterday but no build was triggered.

I am looking into this right now.

**Comment by chmue** [comment]
Somehow the integration with Travis seems to be missing. I cannot access the settings for this repo on Travis anymore. I used to be able to do that without at the beginning of the term...

I might work by (re-)authorising Travis for the LSE-DoM organization. I think I requested access for Travis to the organization and @kbenoit should get an email to approve the request.

**Comment by kbenoit** [comment]
I just granted access.

**Comment by chmue** [comment]
Thank you very much!

The repo was not set as active on Travis anymore. I reactivated it and will now make a dummy change to force a rebuild.

**Comment by chmue** [comment]
Building works fine but `_deploy.sh` is running into problems. Investigating further...

**Comment by chmue** [comment]
The problem seems to be that the personal access token in .travis.yml is not valid anymore.

I don't have enough rights in the `LSE-Methodology` repo to look at or generate a new access token. @kbenoit could you either make me an owner of the orgnization until I finish setting this up or generate a new token with the `repo/public_repo` scope?

![token](https://user-images.githubusercontent.com/421185/33489453-d83369ec-d6ab-11e7-98b6-02ebe678745b.png)

**Comment by kbenoit** [comment]
Done, you’re an owner now.

On 1 Dec 2017, at 16:25, Christian Mueller <notifications@github.com<mailto:notifications@github.com>> wrote:


The problem seems to be that the personal access token in .travis.yml is not valid anymore.

I don't have enough rights in the LSE-Methodology repo to look at or generate a new access token. @kbenoit<https://github.com/kbenoit> could you either make me an owner of the orgnization until I finish setting this up or generate a new token with the repo/public_repo scope?

[token]<https://user-images.githubusercontent.com/421185/33489453-d83369ec-d6ab-11e7-98b6-02ebe678745b.png>

**Comment by chmue** [comment]
Thank you very much Ken!

I found out that you cannot generate a personal access token for an organisation. Any one of us with commit access to this repo would need to create a personal access token which would then also give access to all (!) repos where the user has commit access. That seemed suboptimal to me because it would make sense to use Ken's account but the token would give access to all of Ken's repos which is not ideal.

So I figured out an alternative way to make deployment work again by setting authenticating with a deploy key which can be attached to the repo and only gives access to this one repo. The setup and how to reproduce it if necessary is documented in `devel.md`.

The changes that @jacksojp made are now reflected on the website and in the pdf. This will *hopefully* work automatically again in the future. If something does not work, please [file a new issue](https://github.com/LSE-Methodology/MY451/issues/new) and mention me (@chmue).

Please feel free to remove me as an owner on LSE-Methodology @kbenoit as I don't need the access anymore (and also did not need it in the first place).
